apiVersion: v1
kind: Secret
metadata:
  name: logistics-secrets
  namespace: logistics
type: Opaque
stringData:
  POSTGRES_PASSWORD: "f0d1fe26db001d3c93a5485e"
  REDIS_PASSWORD: ""
  JWT_SECRET_KEY: "tpClUJWoImFSCjmmKndFUtworcsF5V52HyJzgcwTLif7vwaBkzRpuuGEcwXKpL"
  GOOGLE_MAPS_API_KEY: ""
  LINE_CHANNEL_ACCESS_TOKEN: "M1Z9n1sCmxI+Np3ElJpgTYOfgn6nRxpT0ZldhWMLDrBMFwOAfBZqOxkk09ovd8hf3nVL9NvPm+kpmGRHssgPALuYT7suc5YpChkcz5KmabPBeJpsHoRsgaKvh8eCYH0dsBcColINR95TKTb0A2fshgdB04t89/1O/w1cDnyilFU="
  LINE_CHANNEL_SECRET: "bd1a0a1a6cb3c366fec1bdb8224ee1e5"
  API_KEYS: ""
  ADMIN_KEYS: ""
  DISPATCHER_KEYS: ""
